---
title: "Stat Project"
author: "Parijat"
date: "3/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(mgcv)
library(ggplot2)
library(faraway)
library(plyr)
library(Sleuth3)
library(MASS)
library(glmnet)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("~/Desktop/Winter/Hypothesis-Testing-for-Linear-Models/Project/train.RData")
load("~/Desktop/Winter/Hypothesis-Testing-for-Linear-Models/Project/test.RData")
```


# Explanatory Modelling   
### Exploratory Analysis   
```{r}
data_u = data1[,-c(21,3,43,8,29)]
data_i = data1[, c(21,3,43,8,29)]
colnames_datau = colnames(data_u)
colnames_datai = colnames(data_i)


na_count_before = vector(length = dim(data_u)[2])
unique_values = vector(length = dim(data_u)[2])
na_count_after = vector(length = dim(data_u)[2])

lm_complete_case = lm(SalePrice ~ . , data = data_u[,-c(4,48)])
summary_complete_case = summary(lm_complete_case)

data_u_copy = data_u[,]
factors_useful_na = c("Fence","GarageCond","GarageQual","GarageFinish","GarageType","BsmtCond",
                      "BsmtExposure","BsmtQual")

for(col in factors_useful_na){

  column = data_u_copy[,col]
  lvl = levels(data_u_copy[,col])
  levels(data_u_copy[,col]) = c(lvl,"Not_Applicable")
  data_u_copy[is.na(data_u_copy[,col]),col] = "Not_Applicable"
  
}
#
col = "Electrical"
column = data_u_copy[,col]
factor_count = length(table(column))
t = as.data.frame(sort(table(column)))
data_u_copy[is.na(data_u_copy[,col]),col] = t[dim(t)[1],1]



for(col  in c("GarageYrBlt","LotFrontage")){

  data_u_copy[is.na(data_u_copy[,col]),col] = floor(mean(data_u_copy[,col],na.rm = TRUE))
}

# sum(is.na(data_u_copy$Electrical))
# sum(is.na(data_u_copy$LotFrontage))
# sum(is.na(data_u_copy$GarageYrBlt))

lm_mean_amputed = lm(SalePrice ~ . , data = data_u_copy[,-c(4,48)])
summary_amputed = summary(lm_mean_amputed)

summary_amputed$r.squared
summary_complete_case$r.squared
dim(model.matrix(lm_mean_amputed))
```
```{r}
plot_data = data.frame(residual = lm_mean_amputed$residuals, fitted_values = lm_mean_amputed$fitted.values)

ggplot(plot_data, aes(x = residual,y=fitted_values))+geom_point()
```
```{r}
residuals = lm_mean_amputed$residuals
temp_df = cbind(r1 = residuals[-length(residuals)], r2 = residuals[-1])
```
```{r}
qplot(sample = residuals,data = plot_data)
```
```{r}
set.seed(100)

lasso_x_matrix = model.matrix(lm_mean_amputed)[,-1]
lasso_data_matrix = cbind(lasso_x_matrix,"SalePrice" = data_u_copy[,"SalePrice"])

lasso_models = cv.glmnet(lasso_x_matrix,lasso_data_matrix[,"SalePrice"],standardize = TRUE,alpha = 1)

best_lasso_model = glmnet(lasso_x_matrix,lasso_data_matrix[,"SalePrice"],alpha = 1,lambda = lasso_models$lambda.1se)

lasso_model_coef= coef(best_lasso_model)

main_indices = which(lasso_model_coef!=0)


selected_coefficents = c()
rownames_lasso_coef = rownames(lasso_model_coef)

for(i  in main_indices){
  cof = lasso_model_coef[i]
  if(cof!=0 && i>1){
    selected_coefficents = c(selected_coefficents,rownames_lasso_coef[i])
    
  }
}

selected_coefficents
```

## Model Checking and Model Formation
```{r}

selected_matrix = lasso_data_matrix[,c(selected_coefficents,"SalePrice")]
#dim(selected_matrix)
lmod = lm(SalePrice ~ . , data = as.data.frame(selected_matrix))
residuals = lmod$residuals
y_hat = lmod$fitted.values
plot_data_s = data.frame("residuals" = residuals, "y_hat" = y_hat)
ggplot(plot_data_s, aes(x = residuals, y=y_hat))+geom_point()
```
```{r}
qplot(sample = residuals,data = plot_data_s)
```

```{r}
residuals = as.matrix(sort(residuals,decreasing = TRUE))
outliers = as.numeric(rownames(head(residuals)))
outliers


```
```{r}
selected_matrix = selected_matrix[- c(outliers),]
bc = boxcox(SalePrice ~ . , data = as.data.frame(selected_matrix))
```
```{r}
lambda = bc$x[which.max(bc$y)]

y = selected_matrix[,"SalePrice"]
y_tranformed = (y^(lambda) - 1 )/ lambda
selected_matrix[,"SalePrice"] = y_tranformed

lmod = lm(SalePrice ~ . , data = as.data.frame(selected_matrix))


plot_data_s = data.frame("residuals" = lmod$residuals, "y_hat" = lmod$fitted.values)

ggplot(plot_data_s, aes(x = residuals, y=y_hat))+geom_point()
```
```{r}
qplot(sample = residuals,data = plot_data_s)
```
```{r Backward Elimination}
max_pvalue = 1
updated_formula = as.formula("SalePrice ~ .")

while(max_pvalue>0.05 || length(coefficient_names) == 2){
  
  lmod = update(lmod,updated_formula)
  
  summary_lmod = summary(lmod)
  coefficient_names = rownames(summary_lmod$coefficients)
  coefficient_pvalues = summary_lmod$coefficients[,4]
  
  max_pvalue = coefficient_pvalues[which.max(coefficient_pvalues)]
  
  ind = which.max(coefficient_pvalues)[[1]]
  ind
  updated_formula = as.formula(paste("SalePrice ~ ", paste(coefficient_names[-c(1,ind)], collapse= "+")))
  
}

summary_lmod = summary(lmod)
summary_lmod$fstatistic
summary_lmod$r.squared

```
```{r}
plot_data_s = data.frame("residuals" = lmod$residuals, "y_hat" = lmod$fitted.values)
ggplot(plot_data_s, aes(x = residuals, y=y_hat))+geom_point()
```
```{r}
data_i_w = data_i[-outliers,]
final_data_matrix = cbind(data_i_w,model.matrix(lmod)[,-1])
final_data_matrix = cbind(final_data_matrix,"SalePrice"=selected_matrix[,"SalePrice"])

#dim(final_data_matrix)
#colnames(final_data_matrix)
final_lm = lm(SalePrice ~ . , data = final_data_matrix)
#dim(model.matrix(final_lm))
summary_final_lm = summary(final_lm)

coef_values = summary_final_lm$coefficients[,4]
insignificant_vars = names(coef_values[which(coef_values>0.05)])
#length(insignificant_vars)
summary_final_lm
length(rownames(summary_final_lm$coefficients))
dim
```
```{r}

final_data_matrix = model.matrix(final_lm)
#dim(final_data_matrix)
final_data_matrix = cbind(final_data_matrix,"SalePrice" = selected_matrix[,"SalePrice"])
anova_summary = anova(final_lm)
ronames = rownames(anova_summary[which(anova_summary[,5]>0.05),])

final_lm_names = colnames(final_data_matrix)
length(final_lm_names)
reduced_model_names = c()

for(c in final_lm_names){
  if((c %in% ronames) == FALSE){
    reduced_model_names = c(reduced_model_names,c)
  }

}

reduced_model_names = reduced_model_names[-c(1,length(reduced_model_names))]
reduced_model_names
#head(final_data_matrix)
```
```{r}
formulalm = as.formula(paste("SalePrice ~",paste(reduced_model_names,collapse = "+")))
final_lm2 = lm(formulalm,data = as.data.frame(final_data_matrix))
summary(final_lm2)$r.squared

```

```{r}
anova(final_lm,final_lm2)
```

## References 
1. https://www.researchgate.net/post/Comparing_R-squared_values_in_two_models_any_help
